name: Run tests when pushing to any branch, or handling a pull request to master

on:
  push:
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.x"]
      fail-fast: false

    steps:

    - uses: actions/checkout@v3

    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Get full python version
      id: full-python-version
      run: echo version=$(python -c 'import sys; print("-".join(map(str, list(sys.version_info))))') >> $GITHUB_OUTPUT

    - name: Set up cache
      uses: actions/cache@v3
      id: cache
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}

    - name: Install poetry
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry install

    - name: Ensure dependencies are up to date
      if: steps.cache.outputs.cache-hit == 'true'
      run: poetry update

    - name: Run tests
      run: poetry run pytest
